excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
    - Projects/App/Sources/AppDelegate.swift
    - Projects/App/Sources/SceneDelegate.swift
    - Projects/App/Tests/**
    - Projects/Feature/**/AppDelegate.swift
    - Projects/Feature/**/SceneDelegate.swift
    - Projects/FeatureDependency/Sources/Mock/**
    - Tuist
    - Derived
    - Plugins
    - XCConfig
identifier_name:
    min_length:
        warning: 2
        error: 3
    excluded: # 제외할 문자열 목록
        - f
function_body_length:
    warning: 150
    error: 300
type_body_length:
    warning: 400
    error: 500
file_length:
    warning: 1000
    error: 2000
line_length:
    warning: 80
    error: 400
disabled_rules: # 제외하고 싶은 룰
    - trailing_whitespace
    - type_name # 타입명에 _가 들어가면 경고
    - trailing_comma # 배열 마지막 아이템에 ,가 붙으면 경고
    - nesting # 중첩타입
    - cyclomatic_complexity #
    - function_parameter_count #
    - todo #
opt_in_rules:
    - empty_string
